apiVersion: v1
kind: Pod
metadata:
  name: ch0
spec:
  containers:
  - name: nginx
    image: docker.io/nginx:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "4"
      limits:
        memory: "128Mi"
        cpu: "5"
