apiVersion: apps/v1
kind: Deployment
metadata:
  name: ch4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ch4
  template:
    metadata:
      labels:
        app: ch4
    spec:
      containers:
      - name: nginx
        image: docker.io/nginx:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "2"
          limits:
            memory: "128Mi"
            cpu: "3"