apiVersion: apps/v1
kind: Deployment
metadata:
  name: ch2
spec:
  selector:
    matchLabels:
      app: ch2
  replicas: 2
  template:
    metadata:
      labels:
        app: ch2
    spec:
      containers:
      - name: nginx
        image: docker.io/nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 64Mi