apiVersion: apps/v1
kind: Deployment
metadata:
  name: ch1
spec:
  selector:
    matchLabels:
      app: ch1-v2
  replicas: 2
  template:
    metadata:
      labels:
        app: ch1-v2
    spec:
      containers:
      - name: nginx
        image: docker.io/nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 64Mi