apiVersion: apps/v1
kind: Deployment
metadata:
  name: ch5
  labels:
    app: ch5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ch5
  template:
    metadata:
      labels:
        app: ch5
    spec:
      containers:
      - name: ch5
        image: docker.io/balazska/seminar-3-webserver:v3
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 75m
            memory: 128Mi
          requests:
            cpu: 75m
            memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ch5
spec:
  selector:
    app: ch5
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
--- # configure a HPA
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ch5
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ch5
  minReplicas: 1
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 20
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 600
    scaleDown:
      stabilizationWindowSeconds: 300
